# What prefix should be in front of a radio broadcast message?
# The first %s will be the playername
# The second %s will be the message
# Supports '&' colors (http://ess.khhq.net/mc/)
broadcast-format: "[&9&l&nRadio:&r %s] &1%s"

# List of radio tiers
radios:
    # Format is tier: radius
    1: 1000
    2: 3000
    3: 10000
